# Possible values for parameter 'data' with bulk download method
BULK_DATA = [
    "wind",
    "solar",
    "biomass",
    "hydro",
    "gsgk",
    "combustion",
    "nuclear",
    "gas",
    "storage",
    "electricity_consumer",
    "location",
    "market",
    "grid",
    "balancing_area",
    "permit",
    "deleted_units",
    "retrofit_units",
]

# Possible values for parameter 'data' with API download method
API_DATA = [
    "wind",
    "solar",
    "biomass",
    "hydro",
    "gsgk",
    "combustion",
    "nuclear",
    "storage",
    "location",
    "permit",
]

# Technology related values of parameter 'data'
# Methods like Mastr.to_csv() must separate these from additional tables
TECHNOLOGIES = [
    "wind",
    "solar",
    "biomass",
    "hydro",
    "gsgk",
    "combustion",
    "nuclear",
    "storage",
]

# Data which are not related to a specific technology
ADDITIONAL_TABLES = [
    "balancing_area",
    "electricity_consumer",
    "gas_consumer",
    "gas_producer",
    "gas_storage",
    "gas_storage_extended",
    "grid_connections",
    "grids",
    "locations_extended",
    "market_actors",
    "market_roles",
    "permit",
    "deleted_units",
    "retrofit_units",
]

# Possible data types for API download
API_DATA_TYPES = ["unit_data", "eeg_data", "kwk_data", "permit_data"]

# Possible location types for API download
API_LOCATION_TYPES = [
    "location_elec_generation",
    "location_elec_consumption",
    "location_gas_generation",
    "location_gas_consumption",
]

# Map bulk data to bulk download tables (xml file names)
BULK_INCLUDE_TABLES_MAP = {
    "wind": ["anlageneegwind", "einheitenwind"],
    "solar": ["anlageneegsolar", "einheitensolar"],
    "biomass": ["anlageneegbiomasse", "einheitenbiomasse"],
    "hydro": ["anlageneegwasser", "einheitenwasser"],
    "gsgk": [
        "anlageneeggeothermiegrubengasdruckentspannung",
        "einheitengeothermiegrubengasdruckentspannung",
    ],
    "combustion": ["anlagenkwk", "einheitenverbrennung"],
    "nuclear": ["einheitenkernkraft"],
    "storage": ["anlageneegspeicher", "anlagenstromspeicher", "einheitenstromspeicher"],
    "gas": [
        "anlagengasspeicher",
        "einheitengaserzeuger",
        "einheitengasspeicher",
        "einheitengasverbraucher",
    ],
    "electricity_consumer": ["einheitenstromverbraucher"],
    "location": ["lokationen"],
    "market": ["marktakteure", "marktrollen"],
    "grid": ["netzanschlusspunkte", "netze"],
    "balancing_area": ["bilanzierungsgebiete"],
    "permit": ["einheitengenehmigung"],
    "deleted_units": ["geloeschteunddeaktivierteeinheiten"],
    "retrofit_units": ["ertuechtigungen"],
}

# Map bulk data to database table names, for csv export
BULK_ADDITIONAL_TABLES_CSV_EXPORT_MAP = {
    "gas": [
        "gas_consumer",
        "gas_producer",
        "gas_storage",
        "gas_storage_extended",
    ],
    "electricity_consumer": ["electricity_consumer"],
    "location": ["locations_extended"],
    "market": ["market_actors", "market_roles"],
    "grid": ["grid_connections", "grids"],
    "balancing_area": ["balancing_area"],
    "permit": ["permit"],
    "deleted_units": ["deleted_units"],
    "retrofit_units": ["retrofit_units"],
}

# used to map the parameter options in open-mastr to the exact table class names in orm.py
ORM_MAP = {
    "wind": {
        "unit_data": "WindExtended",
        "eeg_data": "WindEeg",
        "permit_data": "Permit",
    },
    "solar": {
        "unit_data": "SolarExtended",
        "eeg_data": "SolarEeg",
        "permit_data": "Permit",
    },
    "biomass": {
        "unit_data": "BiomassExtended",
        "eeg_data": "BiomassEeg",
        "kwk_data": "Kwk",
        "permit_data": "Permit",
    },
    "combustion": {
        "unit_data": "CombustionExtended",
        "kwk_data": "Kwk",
        "permit_data": "Permit",
    },
    "gsgk": {
        "unit_data": "GsgkExtended",
        "eeg_data": "GsgkEeg",
        "kwk_data": "Kwk",
        "permit_data": "Permit",
    },
    "hydro": {
        "unit_data": "HydroExtended",
        "eeg_data": "HydroEeg",
        "permit_data": "Permit",
    },
    "nuclear": {"unit_data": "NuclearExtended", "permit_data": "Permit"},
    "storage": {
        "unit_data": "StorageExtended",
        "eeg_data": "StorageEeg",
        "permit_data": "Permit",
    },
    "gas_consumer": "GasConsumer",
    "gas_producer": "GasProducer",
    "gas_storage": "GasStorage",
    "gas_storage_extended": "GasStorageExtended",
    "electricity_consumer": "ElectricityConsumer",
    "locations_extended": "LocationExtended",
    "market_actors": "MarketActors",
    "market_roles": "MarketRoles",
    "grid_connections": "GridConnections",
    "grids": "Grids",
    "balancing_area": "BalancingArea",
    "permit": "Permit",
    "deleted_units": "DeletedUnits",
    "retrofit_units": "RetrofitUnits",
}


UNIT_TYPE_MAP = {
    "Windeinheit": "wind",
    "Solareinheit": "solar",
    "Biomasse": "biomass",
    "Wasser": "hydro",
    "Geothermie": "gsgk",
    "Verbrennung": "combustion",
    "Kernenergie": "nuclear",
    "Stromspeichereinheit": "storage",
    "Gasspeichereinheit": "gas_storage",
    "Gasverbrauchseinheit": "gas_consumer",
    "Stromverbrauchseinheit": "electricity_consumer",
    "Gaserzeugungseinheit": "gas_producer",
    "Stromerzeugungslokation": "location_elec_generation",
    "Stromverbrauchslokation": "location_elec_consumption",
    "Gaserzeugungslokation": "location_gas_generation",
    "Gasverbrauchslokation": "location_gas_consumption",
}

TRANSLATIONS = {
    'additional_data_requested': {
        'id': 'id',
        'EinheitMastrNummer': 'unitMastrNumber',
        'additional_data_id': 'additional_data_id',
        'technology': 'technology',
        'data_type': 'data_type',
        'request_date': 'request_date'
    },
    'additional_locations_requested': {
        'id': 'id',
        'LokationMastrNummer': 'locationMastrNumber',
        'location_type': 'location_type',
        'request_date': 'request_date'
    },
    'balancing_area': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Id': 'id',
        'Yeic': 'yeic',
        'RegelzoneNetzanschlusspunkt': 'controlZoneNetworkConnectionPoint',
        'BilanzierungsgebietNetzanschlusspunkt': 'accountingAreaNetworkConnectionPoint'
    },
    'basic_units': {
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'Name': 'name',
        'Einheitart': 'unitType',
        'Einheittyp': 'unitCategory',
        'Standort': 'location',
        'Bruttoleistung': 'grossCapacity',
        'Erzeugungsleistung': 'generationCapacity',
        'EinheitBetriebsstatus': 'unitOperationalStatus',
        'Anlagenbetreiber': 'plantOperator',
        'EegMastrNummer': 'eegMastrNumber',
        'KwkMastrNummer': 'kwkMastrNumber',
        'SpeMastrNummer': 'speMastrNumber',
        'GenMastrNummer': 'genMastrNumber',
        'BestandsanlageMastrNummer': 'inventoryPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'EinheitSystemstatus': 'unitSystemStatus'
    },
    'biomass_eeg': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Registrierungsdatum': 'registrationDate',
        'EegMastrNummer': 'eegMastrNumber',
        'Meldedatum': 'notificationDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'EegInbetriebnahmedatum': 'eegCommissioningDate',
        'VerknuepfteEinheit': 'linkedUnit',
        'AnlagenschluesselEeg': 'eegPlantKey',
        'AusschreibungZuschlag': 'tenderAward',
        'AnlagenkennzifferAnlagenregister': 'plantIdentificationNumberRegister',
        'AnlagenkennzifferAnlagenregister_nv': 'plantIdentificationNumberRegister_nv',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'InstallierteLeistung': 'installedCapacity',
        'AusschliesslicheVerwendungBiomasse': 'exclusiveUseOfBiomass',
        'Zuschlagsnummer': 'awardNumber',
        'BiogasInanspruchnahmeFlexiPraemie': 'biogasFlexiPremiumUtilization',
        'BiogasDatumInanspruchnahmeFlexiPraemie': 'biogasFlexiPremiumUtilizationDate',
        'BiogasLeistungserhoehung': 'biogasCapacityIncrease',
        'BiogasDatumLeistungserhoehung': 'biogasCapacityIncreaseDate',
        'BiogasUmfangLeistungserhoehung': 'biogasCapacityIncreaseScope',
        'BiogasGaserzeugungskapazitaet': 'biogasGasProductionCapacity',
        'Hoechstbemessungsleistung': 'maximumRatedCapacity',
        'BiomethanErstmaligerEinsatz': 'biomethaneInitialUse',
        'AnlageBetriebsstatus': 'plantOperatingStatus',
        'BiogasGaserzeugungskapazitaet_nv': 'biogasGasProductionCapacity_na',
        'BiomethanErstmaligerEinsatz_nv': 'biomethaneInitialUse_na'
    },
    'biomass_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzbetreiberMastrNummer': 'gridOperatorMastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'state',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'plotParcelNumbers',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAdditionalInfo',
        'Ort': 'place',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'UtmZonenwert': 'utmZoneValue',
        'UtmEast': 'utmEast',
        'UtmNorth': 'utmNorth',
        'GaussKruegerHoch': 'gaussKruegerHigh',
        'GaussKruegerRechts': 'gaussKruegerRight',
        'Meldedatum': 'notificationDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'temporaryShutdownStartDate',
        'DatumBeendigungVorlaeufigenStilllegung': 'temporaryShutdownEndDate',
        'DatumWiederaufnahmeBetrieb': 'resumptionOfOperationDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'BestandsanlageMastrNummer': 'inventoryPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'AltAnlagenbetreiberMastrNummer': 'oldPlantOperatorMastrNumber',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'NameStromerzeugungseinheit': 'powerGenerationUnitName',
        'Weic': 'weic',
        'WeicDisplayName': 'weicDisplayName',
        'Kraftwerksnummer': 'powerPlantNumber',
        'Energietraeger': 'energySource',
        'Bruttoleistung': 'grossCapacity',
        'Nettonennleistung': 'netCapacity',
        'AnschlussAnHoechstOderHochSpannung': 'connectionToHighVoltageOrExtraHighVoltage',
        'Schwarzstartfaehigkeit': 'blackStartCapability',
        'Inselbetriebsfaehigkeit': 'islandOperationCapability',
        'Einsatzverantwortlicher': 'usageResponsibleEntity',
        'FernsteuerbarkeitNb': 'gridOperatorRemoteControl',
        'FernsteuerbarkeitDv': 'directMarketerRemoteControl',
        'FernsteuerbarkeitDr': 'thirdPartyRemoteControl',
        'Einspeisungsart': 'feedInType',
        'PraequalifiziertFuerRegelenergie': 'prequalifiedForControlEnergy',
        'GenMastrNummer': 'genMastrNumber',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'Hausnummer_nv': 'houseNumber_na',
        'Weic_nv': 'weic_na',
        'Kraftwerksnummer_nv': 'powerPlantNumber_na',
        'Hauptbrennstoff': 'mainFuel',
        'Biomasseart': 'biomassType',
        'Technologie': 'technology',
        'EegMastrNummer': 'eegMastrNumber',
        'KwkMastrNummer': 'kwkMastrNumber'
    },
    'combustion_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzbetreiberMastrNummer': 'gridOperatorMastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'state',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'plotParcelNumbers',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAdditionalInfo',
        'Ort': 'place',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'UtmZonenwert': 'utmZoneValue',
        'UtmEast': 'utmEast',
        'UtmNorth': 'utmNorth',
        'GaussKruegerHoch': 'gaussKruegerHigh',
        'GaussKruegerRechts': 'gaussKruegerRight',
        'Meldedatum': 'notificationDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'temporaryShutdownStartDate',
        'DatumBeendigungVorlaeufigenStilllegung': 'temporaryShutdownEndDate',
        'DatumWiederaufnahmeBetrieb': 'resumptionOfOperationDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'BestandsanlageMastrNummer': 'inventoryPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'AltAnlagenbetreiberMastrNummer': 'oldPlantOperatorMastrNumber',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'NameStromerzeugungseinheit': 'powerGenerationUnitName',
        'Weic': 'weic',
        'WeicDisplayName': 'weicDisplayName',
        'Kraftwerksnummer': 'powerPlantNumber',
        'Energietraeger': 'energySource',
        'Bruttoleistung': 'grossCapacity',
        'Nettonennleistung': 'netCapacity',
        'AnschlussAnHoechstOderHochSpannung': 'connectionToHighVoltageOrExtraHighVoltage',
        'Schwarzstartfaehigkeit': 'blackStartCapability',
        'Inselbetriebsfaehigkeit': 'islandOperationCapability',
        'Einsatzverantwortlicher': 'usageResponsibleEntity',
        #richtg?
        'FernsteuerbarkeitNb': 'remoteControllabilityGridOperator',
        'FernsteuerbarkeitDv': 'remoteControllabilityDistributionNetwork',
        'FernsteuerbarkeitDr': 'remoteControllabilityDirectMarketing',

        'Einspeisungsart': 'feedInType',
        'PraequalifiziertFuerRegelenergie': 'prequalifiedForControlEnergy',
        'GenMastrNummer': 'genMastrNumber',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'Hausnummer_nv': 'houseNumber_na',
        'Weic_nv': 'weic_na',
        'Kraftwerksnummer_nv': 'powerPlantNumber_na',
        'NameKraftwerk': 'powerPlantName',
        'NameKraftwerksblock': 'powerPlantBlockName',
        'DatumBaubeginn': 'constructionStartDate',
        'AnzeigeEinerStilllegung': 'shutdownNotification',
        'ArtDerStilllegung': 'shutdownType',
        'DatumBeginnVorlaeufigenOderEndgueltigenStilllegung': 'startOfTemporaryOrPermanentShutdown',
        'SteigerungNettonennleistungKombibetrieb': 'increaseInNetCapacityCombinedOperation',
        'AnlageIstImKombibetrieb': 'plantIsInCombinedOperation',
        'MastrNummernKombibetrieb': 'mastrNumbersCombinedOperation',
        'NetzreserveAbDatum': 'gridReserveFromDate',
        'SicherheitsbereitschaftAbDatum': 'securityReadinessFromDate',
        'Hauptbrennstoff': 'mainFuel',
        'WeitererHauptbrennstoff': 'additionalMainFuel',
        'WeitereBrennstoffe': 'otherFuels',
        'VerknuepfteErzeugungseinheiten': 'linkedGenerationUnits',
        'BestandteilGrenzkraftwerk': 'partOfBorderPowerPlant',
        'NettonennleistungDeutschland': 'netCapacityGermany',
        'AnteiligNutzungsberechtigte': 'proportionallyAuthorizedUsers',
        'Notstromaggregat': 'emergencyGenerator',
        'Einsatzort': 'placeOfUse',
        'KwkMastrNummer': 'kwkMastrNumber',
        'Technologie': 'technology',
        'AusschliesslicheVerwendungImKombibetrieb': 'exclusiveUseInCombinedOperation'
    },
    'deleted_units': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'Einheittyp': 'unitType',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus'
    },
    'electricity_consumer': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'state',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Ort': 'place',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'Hausnummer_nv': 'houseNumber_na',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAdditionalInfo',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'plotParcelNumbers',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'Registrierungsdatum': 'registrationDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'Einsatzverantwortlicher': 'usageResponsibleEntity',
        'NameStromverbrauchseinheit': 'powerConsumptionUnitName',
        'AnzahlStromverbrauchseinheitenGroesser50Mw': 'numberPowerConsumptionUnitsGreaterThan50Mw',
        'PraequalifiziertGemaessAblav': 'prequalifiedAccordingToAblav',
        'AnteilBeinflussbareLast': 'proportionControllableLoad',
        'ArtAbschaltbareLast': 'typeSwitchableLoad',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'DatumBeginnVoruebergehendeStilllegung': 'startOfTemporaryShutdown',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate'
    },
    'gas_consumer': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'state',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Ort': 'place',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'Hausnummer_nv': 'houseNumber_na',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'Registrierungsdatum': 'registrationDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'NameGasverbrauchsseinheit': 'gasConsumptionUnitName',
        'EinheitDientDerStromerzeugung': 'unitServesElectricityGeneration',
        'MaximaleGasbezugsleistung': 'maximumGasPurchaseCapacity',
        'VerknuepfteEinheit': 'linkedUnit',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Adresszusatz': 'addressAdditionalInfo',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'plotParcelNumbers',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'startOfTemporaryShutdown'
    },
    'gas_producer': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'state',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Ort': 'place',
        'Registrierungsdatum': 'registrationDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'NameGaserzeugungseinheit': 'gasGenerationUnitName',
        'SpeicherMastrNummer': 'storageMastrNumber',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'Hausnummer_nv': 'houseNumber_na',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAdditionalInfo',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'Technologie': 'technology',
        'Erzeugungsleistung': 'generationCapacity',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'plotParcelNumbers',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'DatumBeginnVoruebergehendeStilllegung': 'startOfTemporaryShutdown'
    },
    'gas_storage': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'MastrNummer': 'mastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'Speichername': 'storageName',
        'Registrierungsdatum': 'registrationDate',
        'AnlageBetriebsstatus': 'plantOperatingStatus',
        'VerknuepfteEinheit': 'linkedUnit',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'Inbetriebnahmedatum': 'commissioningDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'NameGasspeicher': 'gasStorageName',
        'Speicherart': 'storageType',
        'MaximalNutzbaresArbeitsgasvolumen': 'maximumUsableWorkingGasVolume',
        'MaximaleEinspeicherleistung': 'maximumInjectionCapacity',
        'MaximaleAusspeicherleistung': 'maximumWithdrawalCapacity',
        'DurchschnittlicherBrennwert': 'averageCalorificValue',
        'Weic': 'weic',
        'Weic_Na': 'weic_na',
        'SpeicherMastrNummer': 'storageMastrNumber',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'plotParcelNumbers',
        'Adresszusatz': 'addressAdditionalInfo',
        'DatumBeginnVoruebergehendeStilllegung': 'startOfTemporaryShutdown',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate'
    },
    'gas_storage_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorReviewStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorReviewDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'federalState',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Ort': 'city',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'Hausnummer_nv': 'houseNumber_na',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'Registrierungsdatum': 'registrationDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperationalStatus',
        'NichtVorhandenInMigriertenEinheiten': 'notAvailableInMigratedUnits',
        'NameGasspeicher': 'gasStorageName',
        'Speicherart': 'storageType',
        'MaximalNutzbaresArbeitsgasvolumen': 'maximumUsableWorkingGasVolume',
        'MaximaleEinspeicherleistung': 'maximumInjectionPower',
        'MaximaleAusspeicherleistung': 'maximumWithdrawalPower',
        'DurchschnittlicherBrennwert': 'averageCalorificValue',
        'Weic': 'weic',
        'Weic_Na': 'weic_Na',
        'SpeicherMastrNummer': 'storageMastrNumber',
        'Gemarkung': 'parish',
        'FlurFlurstuecknummern': 'plotNumbers',
        'Adresszusatz': 'addressAdditional',
        'DatumBeginnVoruebergehendeStilllegung': 'startTemporaryShutdownDate',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate'
    },
    'grid_connections': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzanschlusspunktMastrNummer': 'networkConnectionPointMastrNumber',
        'NetzanschlusspunktBezeichnung': 'networkConnectionPointDescription',
        'LetzteAenderung': 'lastChange',
        'LokationMastrNummer': 'locationMastrNumber',
        'Lokationtyp': 'locationType',
        'MaximaleEinspeiseleistung': 'maximumFeedInPower',
        'Gasqualitaet': 'gasQuality',
        'NetzMastrNummer': 'networkMastrNumber',
        'NochInPlanung': 'stillInPlanning',
        'NameDerTechnischenLokation': 'technicalLocationName',
        'MaximaleAusspeiseleistung': 'maximumWithdrawalPower',
        'Messlokation': 'measurementLocation',
        'Spannungsebene': 'voltageLevel',
        'BilanzierungsgebietNetzanschlusspunktId': 'balancingAreaNetworkConnectionPointId',
        'Nettoengpassleistung': 'netShortCircuitPower',
        'Netzanschlusskapazitaet': 'networkConnectionCapacity'
    },
    'grids': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'MastrNummer': 'mastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'Sparte': 'sector',
        'KundenAngeschlossen': 'customersConnected',
        'GeschlossenesVerteilnetz': 'closedDistributionNetwork',
        'Bezeichnung': 'designation',
        'Marktgebiet': 'marketArea',
        'Bundesland': 'state'
    },
    'gsgk_eeg': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Registrierungsdatum': 'registrationDate',
        'EegMastrNummer': 'eegMastrNumber',
        'Meldedatum': 'notificationDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'EegInbetriebnahmedatum': 'eegCommissioningDate',
        'VerknuepfteEinheit': 'linkedUnit',
        'AnlagenschluesselEeg': 'eegPlantKey',
        'AusschreibungZuschlag': 'tenderAward',
        'AnlagenkennzifferAnlagenregister': 'plantIdentificationNumberPlantRegister',
        'AnlagenkennzifferAnlagenregister_nv': 'plantIdentificationNumberPlantRegister_na',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'InstallierteLeistung': 'installedCapacity',
        'AnlageBetriebsstatus': 'plantOperatingStatus'
    },
    'gsgk_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzbetreiberMastrNummer': 'gridOperatorMastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'state',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'plotParcelNumbers',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAdditionalInfo',
        'Ort': 'place',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'UtmZonenwert': 'utmZoneValue',
        'UtmEast': 'utmEast',
        'UtmNorth': 'utmNorth',
        'GaussKruegerHoch': 'gaussKruegerHigh',
        'GaussKruegerRechts': 'gaussKruegerRight',
        'Meldedatum': 'notificationDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'startOfTemporaryShutdown',
        'DatumBeendigungVorlaeufigenStilllegung': 'endOfTemporaryShutdown',
        'DatumWiederaufnahmeBetrieb': 'resumptionOfOperationDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'BestandsanlageMastrNummer': 'inventoryPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'AltAnlagenbetreiberMastrNummer': 'oldPlantOperatorMastrNumber',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'NameStromerzeugungseinheit': 'electricityGenerationUnitName',
        'Weic': 'weic',
        'WeicDisplayName': 'weicDisplayName',
        'Kraftwerksnummer': 'powerPlantNumber',
        'Energietraeger': 'energySource',
        'Bruttoleistung': 'grossCapacity',
        'Nettonennleistung': 'netCapacity',
        'AnschlussAnHoechstOderHochSpannung': 'connectionToHighVoltageOrExtraHighVoltage',
        'Schwarzstartfaehigkeit': 'blackStartCapability',
        'Inselbetriebsfaehigkeit': 'islandOperationCapability',
        'Einsatzverantwortlicher': 'operationalResponsible',
        'FernsteuerbarkeitNb': 'gridOperatorRemoteControl',
        'FernsteuerbarkeitDv': 'directMarketerRemoteControl',
        'FernsteuerbarkeitDr': 'thirdPartyRemoteControl',
        'Einspeisungsart': 'feedInType',
        'PraequalifiziertFuerRegelenergie': 'prequalifiedForControlEnergy',
        'GenMastrNummer': 'genMastrNumber',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'Hausnummer_nv': 'houseNumber_na',
        'Weic_nv': 'weic_na',
        'Kraftwerksnummer_nv': 'powerPlantNumber_na',
        'Technologie': 'technology',
        'KwkMastrNummer': 'combinedHeatAndPowerMastrNumber',
        'EegMastrNummer': 'eegMastrNumber'
    },
    'hydro_eeg': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Registrierungsdatum': 'registrationDate',
        'EegMastrNummer': 'eegMastrNumber',
        'Meldedatum': 'notificationDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'EegInbetriebnahmedatum': 'eegCommissioningDate',
        'VerknuepfteEinheit': 'linkedUnit',
        'AnlagenschluesselEeg': 'eegPlantKey',
        'AusschreibungZuschlag': 'tenderAward',
        'AnlagenkennzifferAnlagenregister': 'plantIdentificationNumberPlantRegister',
        'AnlagenkennzifferAnlagenregister_nv': 'plantIdentificationNumberPlantRegisterNonVolatile',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'InstallierteLeistung': 'installedCapacity',
        'AnlageBetriebsstatus': 'plantOperatingStatus',
        'Ertuechtigung': 'rehabilitation',
        'ErtuechtigungIds': 'rehabilitationIds'
    },
    'hydro_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzbetreiberMastrNummer': 'gridOperatorMastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'state',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'plotParcelNumbers',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAdditionalInfo',
        'Ort': 'place',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'UtmZonenwert': 'utmZoneValue',
        'UtmEast': 'utmEast',
        'UtmNorth': 'utmNorth',
        'GaussKruegerHoch': 'gaussKruegerHigh',
        'GaussKruegerRechts': 'gaussKruegerRight',
        'Meldedatum': 'notificationDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'startOfTemporaryShutdown',
        'DatumBeendigungVorlaeufigenStilllegung': 'endOfTemporaryShutdown',
        'DatumWiederaufnahmeBetrieb': 'resumptionOfOperationDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'BestandsanlageMastrNummer': 'inventoryPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notFoundInMigratedUnits',
        'AltAnlagenbetreiberMastrNummer': 'oldPlantOperatorMastrNumber',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'NameStromerzeugungseinheit': 'electricityGenerationUnitName',
        'Weic': 'weic',
        'WeicDisplayName': 'weicDisplayName',
        'Kraftwerksnummer': 'powerPlantNumber',
        'Energietraeger': 'energySource',
        'Bruttoleistung': 'grossCapacity',
        'Nettonennleistung': 'netCapacity',
        'AnschlussAnHoechstOderHochSpannung': 'connectionToHighVoltageOrExtraHighVoltage',
        'Schwarzstartfaehigkeit': 'blackStartCapability',
        'Inselbetriebsfaehigkeit': 'islandOperationCapability',
        'Einsatzverantwortlicher': 'operationalResponsible',
        'FernsteuerbarkeitNb': 'gridOperatorRemoteControl',
        'FernsteuerbarkeitDv': 'directMarketerRemoteControl',
        'FernsteuerbarkeitDr': 'thirdPartyRemoteControl',
        'Einspeisungsart': 'feedInType',
        'PraequalifiziertFuerRegelenergie': 'prequalifiedForControlEnergy',
        'GenMastrNummer': 'genMastrNumber',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'Hausnummer_nv': 'houseNumber_na',
        'Weic_nv': 'weic_na',
        'Kraftwerksnummer_nv': 'powerPlantNumber_na',
        'NameKraftwerk': 'powerPlantName',
        'ArtDerWasserkraftanlage': 'typeOfHydroPowerPlant',
        'AnzeigeEinerStilllegung': 'displayOfShutdown',
        'ArtDerStilllegung': 'typeOfShutdown',
        'DatumBeginnVorlaeufigenOderEndgueltigenStilllegung': 'startOfTemporaryOrFinalShutdownDate',
        'MinderungStromerzeugung': 'reductionElectricityGeneration',
        'BestandteilGrenzkraftwerk': 'partOfInterconnectionPlant',
        'NettonennleistungDeutschland': 'netCapacityGermany',
        'ArtDesZuflusses': 'typeOfInflow',
        'EegMastrNummer': 'eegMastrNumber'
    },
    'kwk': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Registrierungsdatum': 'registrationDate',
        'KwkMastrNummer': 'combinedHeatAndPowerPlantMastrNumber',
        'Zuschlagnummer': 'grantNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'Meldedatum': 'reportingDate',
        'ThermischeNutzleistung': 'thermalUtilizationCapacity',
        'ElektrischeKwkLeistung': 'electricalCombinedHeatAndPowerCapacity',
        'VerknuepfteEinheiten': 'linkedUnits',
        'AnlageBetriebsstatus': 'plantOperationalStatus',
        'AusschreibungZuschlag': 'tenderAwardGrant',
        'Netzbetreiberzuordnungen': 'gridOperatorAllocations'
    },
    'locations_basic': {
        'LokationMastrNummer': 'locationMastrNumber',
        'NameDerTechnischenLokation': 'technicalLocationName',
        'Lokationtyp': 'locationType',
        'AnzahlNetzanschlusspunkte': 'numberOfNetworkConnectionPoints'
    },
    'locations_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'MastrNummer': 'mastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'NameDerTechnischenLokation': 'technicalLocationName',
        'VerknuepfteEinheiten': 'linkedUnits',
        'Netzanschlusspunkte': 'networkConnectionPoints',
        'Lokationtyp': 'locationType'
    },
    'market_actors': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'MastrNummer': 'mastrNumber',
        'Personenart': 'personType',
        'Marktfunktion': 'marketFunction',
        'RegistergerichtAusland': 'foreignCommercialRegister',
        'Registernummer': 'registerNumber',
        'DatumLetzeAktualisierung': 'lastUpdateDate',
        'Firmenname': 'companyName',
        'Rechtsform': 'legalForm',
        'Land': 'country',
        'Strasse': 'street',
        'Hausnummer': 'houseNumber',
        'Hausnummer_nv': 'houseNumber_na',
        'Postleitzahl': 'postalCode',
        'Ort': 'city',
        'Bundesland': 'state',
        'Nuts2': 'nuts2',
        'Email': 'email',
        'Telefon': 'phone',
        'Fax_nv': 'fax_na',
        'Webseite_nv': 'website_na',
        'Taetigkeitsbeginn': 'activityStartDate',
        'AcerCode_nv': 'acerCode_na',
        'Umsatzsteueridentifikationsnummer_nv': 'vatIdentificationNumber_na',
        'BundesnetzagenturBetriebsnummer': 'federalNetworkAgencyOperationNumber',
        'BundesnetzagenturBetriebsnummer_nv': 'federalNetworkAgencyOperationNumber_na',
        'HausnummerAnZustelladresse_nv': 'houseNumberForDeliveryAddress_na',
        'Kmu': 'smes',
        'RegistrierungsdatumMarktakteur': 'marketParticipantRegistrationDate',
        'Fax': 'fax',
        'HauptwirtdschaftszweigAbteilung': 'mainEconomicSectorDivision',
        'HauptwirtdschaftszweigGruppe': 'mainEconomicSectorGroup',
        'HauptwirtdschaftszweigAbschnitt': 'mainEconomicSectorSection',
        'Webseite': 'website',
        'Umsatzsteueridentifikationsnummer': 'vatIdentificationNumber',
        'Registergericht': 'commercialRegister',
        'Adresszusatz': 'addressAdditionalInfo',
        'LandAnZustelladresse': 'countryForDeliveryAddress',
        'PostleitzahlAnZustelladresse': 'postalCodeForDeliveryAddress',
        'OrtAnZustelladresse': 'cityForDeliveryAddress',
        'StrasseAnZustelladresse': 'streetForDeliveryAddress',
        'HausnummerAnZustelladresse': 'houseNumberForDeliveryAddress',
        'RegisternummerAusland': 'foreignRegisterNumber',
        'SonstigeRechtsform': 'otherLegalForm',
        'AcerCode': 'acerCode',
        'AdresszusatzAnZustelladresse': 'addressAdditionalInfoForDeliveryAddress',
        'Taetigkeitsende': 'activityEndDate',
        'Region': 'region',
        'Taetigkeitsende_nv': 'activityEndDate_na',
        'Marktrollen': 'marketRoles',
        'Gasgrosshaendler': 'naturalGasWholesaler',
        'BelieferungVonLetztverbrauchernGas': 'supplyToFinalConsumersGas',
        'BelieferungHaushaltskundenGas': 'supplyHouseholdCustomersGas',
        'Netz': 'network',
        'Direktvermarktungsunternehmen': 'directMarketingCompany',
        'BelieferungVonLetztverbrauchernStrom': 'supplyToFinalConsumersElectricity',
        'BelieferungHaushaltskundenStrom': 'supplyHouseholdCustomersElectricity',
        'Stromgrosshaendler': 'electricityWholesaler',
        'MarktakteurVorname': 'marketParticipantFirstName',
        'MarktakteurNachname': 'marketParticipantLastName'
    },
    'market_roles': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'MastrNummer': 'mastrNumber',
        'MarktakteurMastrNummer': 'marketParticipantMastrNumber',
        'Marktrolle': 'marketRole',
        'Marktpartneridentifikationsnummer_nv': 'marketPartnerIdentificationNumber_na',
        'BundesnetzagenturBetriebsnummer': 'federalNetworkAgencyOperationNumber',
        'BundesnetzagenturBetriebsnummer_nv': 'federalNetworkAgencyOperationNumber_na',
        'Marktpartneridentifikationsnummer': 'marketPartnerIdentificationNumber',
        'KontaktdatenMarktrolle': 'marketRoleContactData',
        'DatumLetzteAktualisierung': 'lastUpdateDate'
    },
    'missed_additional_data': {
        'id': 'identifier',
        'additional_data_id': 'additionalDataIdentifier',
        'reason': 'reason',
        'download_date': 'downloadDate'
    },
    'missed_extended_location_data': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'id': 'identifier',
        'LokationMastrNummer': 'locationMastrNumber',
        'reason': 'reason',
        'download_date': 'download_date'
    },
    'nuclear_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzbetreiberMastrNummer': 'gridOperatorMastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'federalState',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityCode',
        'Postleitzahl': 'postalCode',
        'Gemarkung': 'parish',
        'FlurFlurstuecknummern': 'cadastralParcelNumbers',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAddendum',
        'Ort': 'place',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'UtmZonenwert': 'utmZoneValue',
        'UtmEast': 'utmEast',
        'UtmNorth': 'utmNorth',
        'GaussKruegerHoch': 'gaussKruegerHigh',
        'GaussKruegerRechts': 'gaussKruegerRight',
        'Meldedatum': 'reportingDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'temporaryShutdownStartDate',
        'DatumBeendigungVorlaeufigenStilllegung': 'temporaryShutdownEndDate',
        'DatumWiederaufnahmeBetrieb': 'resumptionOfOperationDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperationalStatus',
        'BestandsanlageMastrNummer': 'existingPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notPresentInMigratedUnits',
        'AltAnlagenbetreiberMastrNummer': 'oldPlantOperatorMastrNumber',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'NameStromerzeugungseinheit': 'powerGenerationUnitName',
        'Weic': 'weic',
        'WeicDisplayName': 'weicDisplayName',
        'Kraftwerksnummer': 'powerPlantNumber',
        'Energietraeger': 'energySource',
        'Bruttoleistung': 'grossPowerCapacity',
        'Nettonennleistung': 'netNominalPower',
        'AnschlussAnHoechstOderHochSpannung': 'connectionToHighVoltageOrExtraHighVoltage',
        'Schwarzstartfaehigkeit': 'blackStartCapability',
        'Inselbetriebsfaehigkeit': 'islandOperationCapability',
        'Einsatzverantwortlicher': 'operatorResponsible',
        'FernsteuerbarkeitNb': 'gridOperatorRemoteControl',
        'FernsteuerbarkeitDv': 'directMarketerRemoteControl',
        'FernsteuerbarkeitDr': 'thirdPartyRemoteControl',
        'Einspeisungsart': 'feedInType',
        'PraequalifiziertFuerRegelenergie': 'prequalifiedForRegulationEnergy',
        'GenMastrNummer': 'generationMastrNumber',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'Hausnummer_nv': 'houseNumber_na',
        'Weic_nv': 'weic_na',
        'Kraftwerksnummer_nv': 'powerPlantNumber_na',
        'NameKraftwerk': 'powerPlantName',
        'NameKraftwerksblock': 'powerPlantBlockName',
        'Technologie': 'technology'
    },
    'permit': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Registrierungsdatum': 'registrationDate',
        'GenMastrNummer': 'generationMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'Art': 'type',
        'Datum': 'date',
        'Behoerde': 'authority',
        'Aktenzeichen': 'fileReference',
        'Frist': 'deadline',
        'WasserrechtsNummer': 'waterRightsNumber',
        'WasserrechtAblaufdatum': 'waterRightsExpirationDate',
        'Meldedatum': 'reportingDate',
        'VerknuepfteEinheiten': 'linkedUnits',
        'Frist_nv': 'deadline_na',
        'WasserrechtAblaufdatum_nv': 'waterRightsExpirationDate_na',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments'
    },
    'retrofit_units': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Id': 'id',
        'EegMastrNummer': 'eegMastrNumber',
        'Leistungserhoehung': 'powerIncrease',
        'WiederinbetriebnahmeDatum': 'recommissioningDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'Ertuechtigungsart': 'upgradeType',
        'ErtuechtigungIstZulassungspflichtig': 'upgradeRequiresApproval'
    },
    'solar_eeg': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Registrierungsdatum': 'registrationDate',
        'EegMastrNummer': 'eegMastrNumber',
        'Meldedatum': 'notificationDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'EegInbetriebnahmedatum': 'eegCommissioningDate',
        'VerknuepfteEinheit': 'linkedUnit',
        'AnlagenschluesselEeg': 'eegPlantKey',
        'AusschreibungZuschlag': 'tenderAward',
        'AnlagenkennzifferAnlagenregister': 'plantIdentifierRegister',
        'Zuschlagsnummer': 'awardNumber',
        'AnlageBetriebsstatus': 'plantOperatingStatus',
        'RegistrierungsnummerPvMeldeportal_nv': 'registrationNumberPvReportingPortal_na'
    },
    'solar_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzbetreiberMastrNummer': 'gridOperatorMastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorCheckStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorCheckDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'federalState',
        'Landkreis': 'county',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Gemarkung': 'plot',
        'FlurFlurstuecknummern': 'parcelNumbers',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAddition',
        'Ort': 'place',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'UtmZonenwert': 'utmZoneValue',
        'UtmEast': 'utmEast',
        'UtmNorth': 'utmNorth',
        'GaussKruegerHoch': 'gaussKruegerHigh',
        'GaussKruegerRechts': 'gaussKruegerRight',
        'Meldedatum': 'notificationDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'temporaryShutdownStartDate',
        'DatumBeendigungVorlaeufigenStilllegung': 'temporaryShutdownEndDate',
        'DatumWiederaufnahmeBetrieb': 'resumptionOfOperationDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperatingStatus',
        'BestandsanlageMastrNummer': 'existingPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notPresentInMigratedUnits',
        'AltAnlagenbetreiberMastrNummer': 'oldPlantOperatorMastrNumber',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'NameStromerzeugungseinheit': 'powerGenerationUnitName',
        'Weic': 'weic',
        'WeicDisplayName': 'weicDisplayName',
        'Kraftwerksnummer': 'powerPlantNumber',
        'Energietraeger': 'energySource',
        'Bruttoleistung': 'grossCapacity',
        'Nettonennleistung': 'netCapacity',
        'AnschlussAnHoechstOderHochSpannung': 'connectionToHighVoltageOrExtraHighVoltage',
        'Schwarzstartfaehigkeit': 'blackStartCapability',
        'Inselbetriebsfaehigkeit': 'islandOperationCapability',
        'Einsatzverantwortlicher': 'responsibilityForUse',
        'FernsteuerbarkeitNb': 'gridOperatorRemoteControl',
        'FernsteuerbarkeitDv': 'directMarketerRemoteControl',
        'FernsteuerbarkeitDr': 'thirdPartyRemoteControl',
        'Einspeisungsart': 'feedInType',
        'PraequalifiziertFuerRegelenergie': 'prequalifiedForControlEnergy',
        'GenMastrNummer': 'generationMastrNumber',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'Hausnummer_nv': 'houseNumber_na',
        'Weic_nv': 'weic_na',
        'Kraftwerksnummer_nv': 'powerPlantNumber_na',
        'ZugeordneteWirkleistungWechselrichter': 'assignedReactivePowerInverter',
        'GemeinsamerWechselrichterMitSpeicher': 'sharedInverterWithStorage',
        'AnzahlModule': 'numberOfModules',
        'Lage': 'location',
        'Leistungsbegrenzung': 'powerLimitation',
        'EinheitlicheAusrichtungUndNeigungswinkel': 'uniformOrientationAndTiltAngle',
        'Hauptausrichtung': 'mainOrientation',
        'HauptausrichtungNeigungswinkel': 'mainOrientationTiltAngle',
        'Nebenausrichtung': 'secondaryOrientation',
        'NebenausrichtungNeigungswinkel': 'secondaryOrientationTiltAngle',
        'InAnspruchGenommeneFlaeche': 'areaInUse',
        'ArtDerFlaeche': 'typeOfArea',
        'InAnspruchGenommeneAckerflaeche': 'areaOfAgriculturalLandInUse',
        'Nutzungsbereich': 'usageArea',
        'Buergerenergie': 'communityEnergy',
        'EegMastrNummer': 'eegMastrNumber',
        'ArtDerFlaecheIds': 'typeOfAreaIds'
    },
    'storage_eeg': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Registrierungsdatum': 'registrationDate',
        'EegMastrNummer': 'eegMastrNumber',
        'Meldedatum': 'notificationDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'EegInbetriebnahmedatum': 'eegCommissioningDate',
        'VerknuepfteEinheit': 'linkedUnit',
        'AnlagenschluesselEeg': 'plantKeyEeg',
        'AusschreibungZuschlag': 'auctionBidAward',
        'AnlagenkennzifferAnlagenregister': 'plantIdentifierInPlantRegister',
        'AnlagenkennzifferAnlagenregister_nv': 'plantIdentifierInPlantRegister_na',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'eegAnlagenschluessel': 'eegPlantKey',
        'eegZuschlagsnummer': 'eegAuctionBidNumber',
        'eegAusschreibungZuschlag': 'eegAuctionBidAward'
    },
    'storage_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzbetreiberMastrNummer': 'gridOperatorMastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorReviewStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorReviewDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'federalState',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalKey',
        'Postleitzahl': 'postalCode',
        'Gemarkung': 'plotNumber',
        'FlurFlurstuecknummern': 'cadastralParcelNumbers',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAddition',
        'Ort': 'location',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'UtmZonenwert': 'utmZoneValue',
        'UtmEast': 'utmEast',
        'UtmNorth': 'utmNorth',
        'GaussKruegerHoch': 'gaussKruegerHigh',
        'GaussKruegerRechts': 'gaussKruegerRight',
        'Meldedatum': 'notificationDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'temporaryShutdownStartDate',
        'DatumBeendigungVorlaeufigenStilllegung': 'endOfTemporaryShutdownDate',
        'DatumWiederaufnahmeBetrieb': 'resumptionOfOperationDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperationalStatus',
        'BestandsanlageMastrNummer': 'existingPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notPresentInMigratedUnits',
        'AltAnlagenbetreiberMastrNummer': 'oldPlantOperatorMastrNumber',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'NameStromerzeugungseinheit': 'powerGenerationUnitName',
        'Weic': 'weic',
        'WeicDisplayName': 'weicDisplayName',
        'Kraftwerksnummer': 'powerPlantNumber',
        'Energietraeger': 'energySource',
        'Bruttoleistung': 'grossPowerOutput',
        'Nettonennleistung': 'netNominalPowerOutput',
        'AnschlussAnHoechstOderHochSpannung': 'connectionToHighVoltageOrExtraHighVoltage',
        'Schwarzstartfaehigkeit': 'blackStartCapability',
        'Inselbetriebsfaehigkeit': 'islandOperationCapability',
        'Einsatzverantwortlicher': 'operatorResponsible',
        'FernsteuerbarkeitNb': 'gridOperatorRemoteControl',
        'FernsteuerbarkeitDv': 'directMarketerRemoteControl',
        'FernsteuerbarkeitDr': 'thirdPartyRemoteControl',
        'Einspeisungsart': 'feedInType',
        'PraequalifiziertFuerRegelenergie': 'prequalifiedForGridServices',
        'GenMastrNummer': 'generatorMastrNumber',
        'Hausnummer_nv': 'houseNumber_na',
        'Weic_nv': 'weic_na',
        'Kraftwerksnummer_nv': 'powerPlantNumber_na',
        'Einsatzort': 'deploymentLocation',
        'AcDcKoppelung': 'acDcCoupling',
        'Batterietechnologie': 'batteryTechnology',
        'PumpbetriebLeistungsaufnahme': 'pumpOperationPowerConsumption',
        'PumpbetriebKontinuierlichRegelbar': 'continuousControlOfPumpOperation',
        'Pumpspeichertechnologie': 'pumpedStorageTechnology',
        'Notstromaggregat': 'emergencyGenerator',
        'BestandteilGrenzkraftwerk': 'partOfInterconnectionPlant',
        'NettonennleistungDeutschland': 'netNominalPowerOutputGermany',
        'ZugeordnenteWirkleistungWechselrichter': 'allocatedReactivePowerOfInverter',
        'NutzbareSpeicherkapazitaet': 'usableStorageCapacity',
        'SpeMastrNummer': 'speMastrNumber',
        'EegMastrNummer': 'eegMastrNumber',
        'EegAnlagentyp': 'eegPlantType',
        'Technologie': 'technology'
    },
    'storage_units': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'MastrNummer': 'mastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'NutzbareSpeicherkapazitaet': 'usableStorageCapacity',
        'VerknuepfteEinheit': 'linkedUnit',
        'AnlageBetriebsstatus': 'plantOperationalStatus'
    },
    'wind_eeg': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'Registrierungsdatum': 'registrationDate',
        'EegMastrNummer': 'eegMastrNumber',
        'Meldedatum': 'reportingDate',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'EegInbetriebnahmedatum': 'eegCommissioningDate',
        'VerknuepfteEinheit': 'linkedUnit',
        'AnlagenschluesselEeg': 'eegPlantKey',
        'AusschreibungZuschlag': 'tenderAward',
        'AnlagenkennzifferAnlagenregister': 'plantIdentifierFromPlantRegister',
        'AnlagenkennzifferAnlagenregister_nv': 'plantIdentifierFromPlantRegister_na',
        'Netzbetreiberzuordnungen': 'gridOperatorAssignments',
        'PrototypAnlage': 'prototypePlant',
        'PilotAnlage': 'pilotPlant',
        'InstallierteLeistung': 'installedCapacity',
        'VerhaeltnisErtragsschaetzungReferenzertrag': 'yieldEstimationReferenceYieldRatio',
        'VerhaeltnisReferenzertragErtrag5Jahre': 'referenceYieldRatio5YearsYield',
        'VerhaeltnisReferenzertragErtrag10Jahre': 'referenceYieldRatio10YearsYield',
        'VerhaeltnisReferenzertragErtrag15Jahre': 'referenceYieldRatio15YearsYield',
        'Zuschlagsnummer': 'awardNumber',
        'AnlageBetriebsstatus': 'plantOperationalStatus',
        'VerhaeltnisErtragsschaetzungReferenzertrag_nv': 'yieldEstimationReferenceYieldRatio_na',
        'VerhaeltnisReferenzertragErtrag5Jahre_nv': 'referenceYieldRatio5YearsYield_na',
        'VerhaeltnisReferenzertragErtrag10Jahre_nv': 'referenceYieldRatio10YearsYield_na',
        'VerhaeltnisReferenzertragErtrag15Jahre_nv': 'referenceYieldRatio15YearsYield_na'
    },
    'wind_extended': {
        'DatenQuelle': 'dataSource',
        'DatumDownload': 'downloadDate',
        'NetzbetreiberMastrNummer': 'gridOperatorMastrNumber',
        'Registrierungsdatum': 'registrationDate',
        'EinheitMastrNummer': 'unitMastrNumber',
        'DatumLetzteAktualisierung': 'lastUpdateDate',
        'LokationMastrNummer': 'locationMastrNumber',
        'NetzbetreiberpruefungStatus': 'gridOperatorReviewStatus',
        'NetzbetreiberpruefungDatum': 'gridOperatorReviewDate',
        'AnlagenbetreiberMastrNummer': 'plantOperatorMastrNumber',
        'Land': 'country',
        'Bundesland': 'federalState',
        'Landkreis': 'district',
        'Gemeinde': 'municipality',
        'Gemeindeschluessel': 'municipalityKey',
        'Postleitzahl': 'postalCode',
        'Gemarkung': 'parish',
        'FlurFlurstuecknummern': 'plotNumbers',
        'Strasse': 'street',
        'StrasseNichtGefunden': 'streetNotFound',
        'Hausnummer': 'houseNumber',
        'HausnummerNichtGefunden': 'houseNumberNotFound',
        'Adresszusatz': 'addressAdditional',
        'Ort': 'city',
        'Laengengrad': 'longitude',
        'Breitengrad': 'latitude',
        'UtmZonenwert': 'utmZoneValue',
        'UtmEast': 'utmEast',
        'UtmNorth': 'utmNorth',
        'GaussKruegerHoch': 'gaussKruegerHigh',
        'GaussKruegerRechts': 'gaussKruegerRight',
        'Meldedatum': 'notificationDate',
        'GeplantesInbetriebnahmedatum': 'plannedCommissioningDate',
        'Inbetriebnahmedatum': 'commissioningDate',
        'DatumEndgueltigeStilllegung': 'finalShutdownDate',
        'DatumBeginnVoruebergehendeStilllegung': 'temporaryShutdownStartDate',
        'DatumBeendigungVorlaeufigenStilllegung': 'endTemporaryShutdownDate',
        'DatumWiederaufnahmeBetrieb': 'restartOperationDate',
        'EinheitSystemstatus': 'unitSystemStatus',
        'EinheitBetriebsstatus': 'unitOperationalStatus',
        'BestandsanlageMastrNummer': 'existingPlantMastrNumber',
        'NichtVorhandenInMigriertenEinheiten': 'notAvailableInMigratedUnits',
        'AltAnlagenbetreiberMastrNummer': 'oldPlantOperatorMastrNumber',
        'DatumDesBetreiberwechsels': 'operatorChangeDate',
        'DatumRegistrierungDesBetreiberwechsels': 'operatorChangeRegistrationDate',
        'NameStromerzeugungseinheit': 'powerGenerationUnitName',
        'Weic': 'weic',
        'WeicDisplayName': 'weicDisplayName',
        'Kraftwerksnummer': 'powerPlantNumber',
        'Energietraeger': 'energySource',
        'Bruttoleistung': 'grossCapacity',
        'Nettonennleistung': 'netCapacity',
        'AnschlussAnHoechstOderHochSpannung': 'connectionToHighVoltageOrExtraHighVoltage',
        'Schwarzstartfaehigkeit': 'blackStartCapability',
        'Inselbetriebsfaehigkeit': 'islandOperationCapability',
        'Einsatzverantwortlicher': 'operatingEntity',
        'FernsteuerbarkeitNb': 'gridOperatorRemoteControl',
        'FernsteuerbarkeitDv': 'directMarketerRemoteControl',
        'FernsteuerbarkeitDr': 'thirdPartyRemoteControl',
        'Einspeisungsart': 'feedInType',
        'PraequalifiziertFuerRegelenergie': 'prequalifiedForControlEnergy',
        'GenMastrNummer': 'genMastrNumber',
        'Hausnummer_nv': 'houseNumber_na',
        'Weic_nv': 'weic_na',
        'Kraftwerksnummer_nv': 'powerPlantNumber_na',
        'NameWindpark': 'windFarmName',
        'Lage': 'location',
        'Seelage': 'locationAtSea',
        'ClusterOstsee': 'clusterBalticSea',
        'ClusterNordsee': 'clusterNorthSea',
        'Hersteller': 'manufacturer',
        'HerstellerId': 'manufacturerId',
        'Technologie': 'technology',
        'Typenbezeichnung': 'modelDesignation',
        'Nabenhoehe': 'hubHeight',
        'Rotordurchmesser': 'rotorDiameter',
        'Rotorblattenteisungssystem': 'bladeIcingSystem',
        'AuflageAbschaltungLeistungsbegrenzung': 'requirementShutdownPowerLimitation',
        'AuflagenAbschaltungSchallimmissionsschutzNachts': 'requirementShutdownNoiseProtectionNight',
        'AuflagenAbschaltungSchallimmissionsschutzTagsueber': 'requirementShutdownNoiseProtectionDay',
        'AuflagenAbschaltungSchattenwurf': 'requirementShutdownShadowThrow',
        'AuflagenAbschaltungTierschutz': 'requirementShutdownAnimalProtection',
        'AuflagenAbschaltungEiswurf': 'requirementShutdownIceThrow',
        'AuflagenAbschaltungSonstige': 'requirementShutdownOther',
        'Wassertiefe': 'waterDepth',
        'Kuestenentfernung': 'distanceToCoast',
        'Buergerenergie': 'citizensEnergy',
        'Nachtkennzeichen': 'nightIdentifier',
        'EegMastrNummer': 'eegMastrNumber'
    }
}
