columns_replace_list=[
    #anlageneegsolar
    "AnlageBetriebsstatus",
    #anlageneegspeicher
    #anlagenstromspeicher
    #einheitensolar
    "Land",
    "Bundesland",
    "EinheitSystemstatus",
    "EinheitBetriebsstatus",
    "Energietraeger",
    "Einspeisungsart",
    "GemeinsamerWechselrichterMitSpeicher",
    "Lage",
    "Leistungsbegrenzung",
    "Hauptausrichtung",
    "HauptausrichtungNeigungswinkel",
    "Nutzungsbereich",
    "Nebenausrichtung",
    "NebenausrichtungNeigungswinkel",
    "ArtDerFlaecheIds",
    #einheitenstromspeicher
    "AcDcKoppelung",
    "Batterietechnologie",
    "Technologie",
    "Pumpspeichertechnologie",
    #lokationen
    #marktakteure
    "Personenart",
    "Rechtsform",
    "HauptwirtdschaftszweigAbteilung",
    "HauptwirtdschaftszweigGruppe",
    "HauptwirtdschaftszweigAbschnitt",
    "Registergericht",
    "LandAnZustelladresse",
    #netzanschlusspunkte
    "Gasqualitaet",
    "Spannungsebene",
    #anlageneegbiomasse
    #anlageneeggeosolarthermiegrubenklaerschlammdruckentspannung
    #anlageneegwasser
    #anlageneegwind
    #anlagengasspeicher
    #anlagenkwk
    #bilanzierungsgebiete
    #einheitenbiomasse
    "Hauptbrennstoff",
    "Biomasseart",
    #einheitengaserzeuger
    #einheitengasspeicher
    "Speicherart",
    #einheitengasverbraucher
    #einheitengenehmigung
    "Art",
    #einheitengeosolarthermiegrubenklaerschlammdruckentspannung
    #einheitenkernkraft
    #einheitenstromverbraucher
    #einheitentypen
    #einheitenverbrennung
    "WeitererHauptbrennstoff",
    "WeitereBrennstoffe",
    "ArtDerStilllegung",
    #einheitenwasser
    "ArtDesZuflusses",
    #marktrollen
    #netze
    "Sparte",
    #einheitenwind
    "Lage",
    "Hersteller",
    "Seelage",
    "ClusterNordsee",
    "ClusterOstsee",
]